/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type UsecasesSchema = UsecasesFileInterface;
export type UsecasesFileInterface = UsecaseCategory[];

export interface UsecaseCategory {
  title: string;
  id: string;
  usecases: UsecaseItem[];
  groups?: UsecaseGroup[];
}
export interface UsecaseItem {
  id: string;
  title: string;
  description: string;
  experience: ["all" | "power" | "experts" | "code"] | null;
  maturity: ["experimental" | "beta"] | null;
  access: ["hpc" | "byor"] | null;
  disabled: boolean;
  implementation: "webapp" | "ipynb";
  contributors: Contributors[];
  picture: {
    src: string;
    [k: string]: unknown;
  };
  dataProtected: boolean;
  externalUrl?: string;
  chooseModel?: boolean;
  tutorial?: string | null;
  notebookPath?: string;
  notebookRepoUrl?: string;
}
export interface Contributors {
  name: string;
  email: string;
}
export interface UsecaseGroup {
  title: string;
  items: [UsecaseItem, ...UsecaseItem[]];
  [k: string]: unknown;
}
