name: Github Pages Dev

on: [push]

jobs:
  dev-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Run tests
        run: |
          npm install
          npm run validate
          npm run test

      - name: Install and Build Development
        run: |
          BASE_URL="/ebrains-wizard/dev" npm run build

      - name: Deploy Development
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: public/build
          target-folder: dev
