name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install and Build Production
        run: |
          npm install
          BASE_URL="/ebrains-wizard" npm run build
          cp public/service-worker.js public/build

      - name: Deploy Production
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public/build # The folder the action should deploy.
