name: Github Pages Dev

on: [push]

jobs:
  dev-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Run tests
        run: |
          npm install
          npm run validate
          npm run test

      - name: Install and Build Development
        run: |
          BASE_URL="/ebrains-wizard/dev" npm run build
          cp public/service-worker.js public/build

      - name: Deploy Development
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: public/build
          target-folder: dev

      - name: Show deployment url
        run: |
          echo "Deployed at https://antonelepfl.github.io/ebrains-wizard/dev/"
